import = [
  # alacritty themes
  # "~/.config/alacritty/themes/themes/coolnight.toml",
  # custom theme
  "~/.config/alacritty/custom/themes/coolnight.toml",
]

[ env ]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
offset.y = 10
glyph_offset.y = 5

size = 14
