[ env ]
TERM = "xterm-256color"

# [shell]
# program = "/opt/homebrew/bin/zellij"
# args = ["-l", "welcome"]

[window]
# startup_mode = "SimpleFullscreen"
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 14

[colors]
primary.background = "#000000"

[general]
import = [
  # alacritty themes
  # "~/.config/alacritty/themes/themes/coolnight.toml",
  # catppuccin themes
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
  # custom theme
  # "~/.config/alacritty/custom/themes/coolnight.toml",
]
