#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

dir_length = 2

[[wildcard]]
pattern = "~/Sites/**"
startup_command = "nvim"
windows = [ "dev", "ai" ]

[[window]]
name = "dev"
startup_script = "tmux split-window -h -t 2"

[[window]]
name = "ai"
startup_script = "opencode"
